site_name: AI-Driven Applications
site_description: Documentation for AI-Driven Applications Suite
site_author: CosmasLabs
repo_url: https://github.com/yourusername/repository
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
  - git-revision-date
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
    - First Steps: getting-started/first-steps.md
  - Projects:
    - AI Crypto Price Predictor:
      - Overview: projects/crypto-predictor/overview.md
      - Architecture: projects/crypto-predictor/architecture.md
      - API Reference: projects/crypto-predictor/api.md
    - Document OCR System:
      - Overview: projects/ocr-system/overview.md
      - Architecture: projects/ocr-system/architecture.md
      - API Reference: projects/ocr-system/api.md
    - Marketing Analytics Tool:
      - Overview: projects/marketing-analytics/overview.md
      - Architecture: projects/marketing-analytics/architecture.md
      - API Reference: projects/marketing-analytics/api.md
  - NocoBase Integration:
    - Setup: nocobase/setup.md
    - Configuration: nocobase/configuration.md
    - Customization: nocobase/customization.md
  - Development:
    - Setup: development/setup.md
    - Guidelines: development/guidelines.md
    - Testing: development/testing.md
    - CI/CD: development/ci-cd.md
  - Deployment:
    - Requirements: deployment/requirements.md
    - Docker: deployment/docker.md
    - Kubernetes: deployment/kubernetes.md
    - Monitoring: deployment/monitoring.md
  - Contributing:
    - Guidelines: contributing/guidelines.md
    - Code of Conduct: contributing/code-of-conduct.md
    - Development Process: contributing/development-process.md
  - Security:
    - Overview: security/overview.md
    - Best Practices: security/best-practices.md
    - Vulnerability Reporting: security/vulnerability-reporting.md
  - API Reference:
    - Authentication: api/authentication.md
    - Endpoints: api/endpoints.md
    - WebSocket: api/websocket.md
    - Rate Limiting: api/rate-limiting.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/yourusername
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  consent:
    title: Cookie consent
    description: >
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  version:
    provider: mike
